runtime: nodejs18

instance_class: F1
env: standard

handlers:
  - url: /.*
    script: auto

automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
  min_instances: 1
  max_instances: 5
